language: bash
services: docker

os: linux
arch:
  - arm64

env:
  matrix:
    - PHP_VERSION=8 LIBXML_VERSION=2.9.12
    - PHP_VERSION=8 LIBXML_VERSION=2.9.10
    - PHP_VERSION=8 LIBXML_VERSION=2.9.5
    - PHP_VERSION=8 LIBXML_VERSION=2.9.4
    - PHP_VERSION=7.4 LIBXML_VERSION=2.9.12
    - PHP_VERSION=7.4 LIBXML_VERSION=2.9.10
    - PHP_VERSION=7.4 LIBXML_VERSION=2.9.5
    - PHP_VERSION=7.4 LIBXML_VERSION=2.9.4
    - PHP_VERSION=7.3 LIBXML_VERSION=2.9.12
    - PHP_VERSION=7.3 LIBXML_VERSION=2.9.10
    - PHP_VERSION=7.3 LIBXML_VERSION=2.9.5
    - PHP_VERSION=7.3 LIBXML_VERSION=2.9.4

matrix:
  allow_failures:
    - env: PHP_VERSION=8 LIBXML_VERSION=2.9.12
    - env: PHP_VERSION=8 LIBXML_VERSION=2.9.10
    - env: PHP_VERSION=8 LIBXML_VERSION=2.9.5
    - env: PHP_VERSION=8 LIBXML_VERSION=2.9.4
    - env: PHP_VERSION=7.4 LIBXML_VERSION=2.9.12
    - env: PHP_VERSION=7.4 LIBXML_VERSION=2.9.10
    - env: PHP_VERSION=7.4 LIBXML_VERSION=2.9.5
    - env: PHP_VERSION=7.4 LIBXML_VERSION=2.9.4
    - env: PHP_VERSION=7.3 LIBXML_VERSION=2.9.12
    - env: PHP_VERSION=7.3 LIBXML_VERSION=2.9.10
    - env: PHP_VERSION=7.3 LIBXML_VERSION=2.9.5
    - env: PHP_VERSION=7.3 LIBXML_VERSION=2.9.4

install:
  - docker run --rm --volume $PWD:/app --workdir="/app" composer install

script:
  - docker build --build-arg PHP_VERSION=${PHP_VERSION} --build-arg LIBXML_VERSION=${LIBXML_VERSION} --build-arg XDEBUG_VERSION=${XDEBUG_VERSION} -t travis-build - < ./docker/php/Dockerfile
  - docker run --volume $PWD:/app --workdir="/app" travis-build php ./vendor/bin/phpunit --coverage-clover /app/test/clover.xml

after_script:
  - docker run --volume $PWD:/app --workdir="/app" composer require php-coveralls/php-coveralls:^2.0
  - docker run --volume $PWD:/app --workdir="/app" --env TRAVIS=${TRAVIS} --env TRAVIS_JOB_ID=${TRAVIS_JOB_ID} travis-build php ./vendor/php-coveralls/php-coveralls/bin/php-coveralls -v
